### PR TITLE
headers

### PR DESCRIPTION
**Pull request by tsurdilo**
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>

**Many thanks for submitting your Pull Request :heart:!**

**What this PR does / why we need it**:

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@antmendoza is this how you do headers ? :)

**Comment by antmendoza** [comment]
honestly, I don't know @tsurdilo 😅 , I am going to read about it

**Comment by tsurdilo** [comment]
closing this, we can revisit later

**Comment by antmendoza** [comment]
sorry @tsurdilo, I had forgotten about this

**Comment by tsurdilo** [comment]
no problem at all :)

**Pull request closed without merging**
